### ISSUE TITLE
bug in testing the model block

### ISSUE THREAD

**Issue by lilihub** [adezfouli/tutorials#2] opened 2020-12-04 08:01 UTC
![image](https://user-images.githubusercontent.com/37544742/101137311-99749900-3649-11eb-9695-6db14792d08c.png)
I set the step as 10, but there are still errors
![image](https://user-images.githubusercontent.com/37544742/101137515-eb1d2380-3649-11eb-920c-baab12b531ce.png)

**Comment by adezfouli** [comment] 2020-12-10 03:35
It works on my end. Are you using the correct TensorFlow version?

**Comment by lilihub** [comment] 2020-12-10 04:05
Thanks so much for your reply! Will check it later.

**Comment by zashwood** [comment] 2022-02-03 21:19
Hi @adezfouli Thanks for this tutorial!  It's awesome.  I just wanted to confirm that I also encountered the issue that @lilihub reports here.  The issue is that `initial_rnn_state` is not updated in the "Testing the model" cell, so the first dimension is still the batch size of the training data, as opposed to the batch size of the test data.  Adding the line ```initial_rnn_state = np.zeros((reward_action.shape[0], n_cells,), dtype=np.float32)``` before the `model.evaluate` line fixed the problem for me.

**Comment by adezfouli** [comment] 2022-02-04 02:37
Hi @zashwood , thank you very much for pointing this out -- I just fixed this.
@lilihub : sorry I missed this earlier; should be fixed now thanks to Zoe's comment.

**Closed as completed** 2022-02-04 02:37 UTC
